// Decompiled with JetBrains decompiler
// Type: TSN.Native.Enums.Win32Error
// Assembly: TheToonTownSpoofer, Version=6.0.0.0, Culture=neutral, PublicKeyToken=599186c172bd0364
// MVID: B039A871-4CC9-4341-8B41-AC2E69DB4046
// Assembly location: C:\Program Files (x86)\The Spoof Net\The ToonTown Spoofer V6\TheToonTownSpoofer.exe

namespace TSN.Native.Enums
{
  public enum Win32Error : uint
  {
    Success = 0,
    InvalidFunction = 1,
    FileNotFound = 2,
    PathNotFound = 3,
    TooManyOpenFiles = 4,
    AccessDenied = 5,
    InvalidHandle = 6,
    ArenaTrashed = 7,
    NotEnoughMemory = 8,
    InvalidBlock = 9,
    BadEnvironment = 10,
    BadFormat = 11,
    InvalidAccess = 12,
    InvalidData = 13,
    OutOfMemory = 14,
    InvalidDrive = 15,
    CurrentDirectory = 16,
    NotSameDevice = 17,
    NoMoreFiles = 18,
    WriteProtect = 19,
    BadUnit = 20,
    NotReady = 21,
    BadCommand = 22,
    Crc = 23,
    BadLength = 24,
    Seek = 25,
    NotDosDisk = 26,
    SectorNotFound = 27,
    OutOfPaper = 28,
    WriteFault = 29,
    ReadFault = 30,
    GenFailure = 31,
    SharingViolation = 32,
    LockViolation = 33,
    WrongDisk = 34,
    SharingBufferExceeded = 36,
    HandleEof = 38,
    HandleDiskFull = 39,
    NotSupported = 50,
    RemNotList = 51,
    DupName = 52,
    BadNetPath = 53,
    NetworkBusy = 54,
    DevNotExist = 55,
    TooManyCmds = 56,
    FileExists = 80,
    CannotMake = 82,
    AlreadyAssigned = 85,
    InvalidPassword = 86,
    InvalidParameter = 87,
    NetWriteFault = 88,
    NoProcSlots = 89,
    TooManySemaphores = 100,
    ExclSemAlreadyOwned = 101,
    SemIsSet = 102,
    TooManySemRequests = 103,
    InvalidAtInterruptTime = 104,
    SemOwnerDied = 105,
    SemUserLimit = 106,
    Canceled = 1223,
  }
}
